Repository Kernel360/KDEV4-WHERE-CAR-BE, pull requests merged in 2025-03, with the labels that each got.

#12 [#11] refactor: 엔티티 이름 및 필드 수정
  rest/src/main/java/com/wherecar/rest/domain/BaseEntity.java
  rest/src/main/java/com/wherecar/rest/domain/Car.java
  rest/src/main/java/com/wherecar/rest/domain/Company.java
  rest/src/main/java/com/wherecar/rest/domain/GeoInfo.java
  rest/src/main/java/com/wherecar/rest/domain/GeoLog.java
  rest/src/main/java/com/wherecar/rest/domain/GpsLog.java
  rest/src/main/java/com/wherecar/rest/domain/OnOffLog.java
  rest/src/main/java/com/wherecar/rest/domain/User.java
  rest/src/main/resources/application.properties
Labels: 🔨 Refactor

#15 [#13] modify: 엔티티 필드 수정
  rest/src/main/java/com/wherecar/rest/domain/Car.java
  rest/src/main/java/com/wherecar/rest/domain/OnOffLog.java
  rest/src/main/java/com/wherecar/rest/domain/User.java
Labels: ✏️ Modify

#17 [#16] feat: 프로젝트 폴더 구조 추가
  rest/src/main/java/com/wherecar/rest/config/.empty
  rest/src/main/java/com/wherecar/rest/controller/.empty
  rest/src/main/java/com/wherecar/rest/dto/.empty
  rest/src/main/java/com/wherecar/rest/jwt/.empty
  rest/src/main/java/com/wherecar/rest/repository/.empty
  rest/src/main/java/com/wherecar/rest/service/.empty
Labels: ✨ Feature, 🏷️ Rename

#19 [#18] feat: Collector 프로젝트 폴더 구조 추가
  collector/src/main/java/com/wherecar/collector/config/.empty
  collector/src/main/java/com/wherecar/collector/controller/.empty
  collector/src/main/java/com/wherecar/collector/domain/AcquisitionType.java
  collector/src/main/java/com/wherecar/collector/domain/BaseEntity.java
  collector/src/main/java/com/wherecar/collector/domain/Car.java
  collector/src/main/java/com/wherecar/collector/domain/Company.java
  collector/src/main/java/com/wherecar/collector/domain/GeoInfo.java
  collector/src/main/java/com/wherecar/collector/domain/GeoLog.java
  collector/src/main/java/com/wherecar/collector/domain/GpsLog.java
  collector/src/main/java/com/wherecar/collector/domain/OnOffLog.java
  collector/src/main/java/com/wherecar/collector/domain/OwnerType.java
  collector/src/main/java/com/wherecar/collector/domain/User.java
  collector/src/main/java/com/wherecar/collector/dto/.empty
  collector/src/main/java/com/wherecar/collector/jwt/.empty
  collector/src/main/java/com/wherecar/collector/repository/.empty
  collector/src/main/java/com/wherecar/collector/service/.empty
Labels: ✨ Feature, 🏷️ Rename

#21 [#20] feat: emulator 초기 프로젝트 설정
  .gitignore
  emulator/.gitattributes
  emulator/build.gradle
  emulator/gradle/wrapper/gradle-wrapper.jar
  emulator/gradle/wrapper/gradle-wrapper.properties
  emulator/gradlew
  emulator/gradlew.bat
  emulator/settings.gradle
  emulator/src/main/java/com/where_car/emulator/EmulatorApplication.java
  emulator/src/main/java/com/where_car/emulator/device/controller/.keep
  emulator/src/main/java/com/where_car/emulator/device/domain/.keep
  emulator/src/main/java/com/where_car/emulator/device/dto/.keep
  emulator/src/main/java/com/where_car/emulator/device/mapper/.keep
  emulator/src/main/java/com/where_car/emulator/device/repository/.keep
  emulator/src/main/java/com/where_car/emulator/device/service/.keep
  emulator/src/main/java/com/where_car/emulator/global/config/.keep
  emulator/src/main/java/com/where_car/emulator/global/error/.keep
  emulator/src/main/java/com/where_car/emulator/global/infra/.keep
  emulator/src/main/resources/application-dev.yml
  emulator/src/main/resources/application.yml
  emulator/src/test/java/com/where_car/emulator/EmulatorApplicationTests.java
  settings.gradle
Labels: ✨ Feature, 📦️ package

#26 [#14] feat: car CRUD api 구현
  rest/src/main/java/com/wherecar/rest/constants/PaginationConstants.java
  rest/src/main/java/com/wherecar/rest/controller/CarController.java
  rest/src/main/java/com/wherecar/rest/domain/Car.java
  rest/src/main/java/com/wherecar/rest/dto/CarRegisterRequest.java
  rest/src/main/java/com/wherecar/rest/dto/CarResponse.java
  rest/src/main/java/com/wherecar/rest/repository/CarRepository.java
  rest/src/main/java/com/wherecar/rest/service/CarService.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
Labels: ✨ Feature

#24 [#23] feat: add security config
  rest/src/main/java/com/wherecar/rest/config/SecurityConfig.java
Labels: ✨ Feature

#36 [#35] Refactor : car api 메소드명 수정
  rest/src/main/java/com/wherecar/rest/controller/CarController.java
  rest/src/main/java/com/wherecar/rest/service/CarService.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
Labels: 🔨 Refactor

#33 [#10] feat: company RUD 생성
  rest/src/main/java/com/wherecar/rest/controller/CompanyController.java
  rest/src/main/java/com/wherecar/rest/domain/Company.java
  rest/src/main/java/com/wherecar/rest/dto/CompanyRequest.java
  rest/src/main/java/com/wherecar/rest/dto/CompanyResponse.java
  rest/src/main/java/com/wherecar/rest/repository/CompanyRepository.java
  rest/src/main/java/com/wherecar/rest/service/CompanyService.java
  rest/src/main/java/com/wherecar/rest/service/CompanyServiceImpl.java
Labels: ✨ Feature

#45 [#43] refactor: 차량 수정 API 수정 로직 change 메소드로 변경
  rest/src/main/java/com/wherecar/rest/domain/Car.java
  rest/src/main/java/com/wherecar/rest/service/CarService.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
Labels: 🔨 Refactor

#54 [#53] feat: permission 관련 기능 추가
  rest/src/main/java/com/wherecar/rest/user/auth/AuthUtil.java
  rest/src/main/java/com/wherecar/rest/user/controller/UserController.java
  rest/src/main/java/com/wherecar/rest/user/domain/Permission.java
  rest/src/main/java/com/wherecar/rest/user/domain/PermissionType.java
  rest/src/main/java/com/wherecar/rest/user/domain/User.java
  rest/src/main/java/com/wherecar/rest/user/domain/UserPermission.java
  rest/src/main/java/com/wherecar/rest/user/dto/PermissionRequest.java
  rest/src/main/java/com/wherecar/rest/user/dto/PermissionResponse.java
  rest/src/main/java/com/wherecar/rest/user/permissionCheck/PermissionCheckAspect.java
  rest/src/main/java/com/wherecar/rest/user/permissionCheck/RequiredPermission.java
  rest/src/main/java/com/wherecar/rest/user/repository/PermissionRepository.java
  rest/src/main/java/com/wherecar/rest/user/repository/UserRepository.java
  rest/src/main/java/com/wherecar/rest/user/security/CustomUserDetails.java
  rest/src/main/java/com/wherecar/rest/user/security/JWTFilter.java
  rest/src/main/java/com/wherecar/rest/user/security/LoginFilter.java
  rest/src/main/java/com/wherecar/rest/user/service/UserService.java
  rest/src/main/java/com/wherecar/rest/user/service/UserServiceImpl.java
Labels: 🐞 Bugfix, ✨ Feature

#57 [#56] chore: pr 댓글 자동추가 삭제
  .github/workflows/reviewer-auto-registration.yml
Labels: ⚙ Chore
