Repository Kernel360/KDEV4-WHERE-CAR-BE, pull requests merged in 2025-04, with the labels that each got.

#47 [#27] feat: carLog 조회 및 수정 API 구현
  rest/src/main/java/com/wherecar/rest/controller/CarController.java
  rest/src/main/java/com/wherecar/rest/controller/CarLogController.java
  rest/src/main/java/com/wherecar/rest/domain/Car.java
  rest/src/main/java/com/wherecar/rest/domain/CarLog.java
  rest/src/main/java/com/wherecar/rest/domain/CarState.java
  rest/src/main/java/com/wherecar/rest/domain/CarStatus.java
  rest/src/main/java/com/wherecar/rest/domain/GpsConditionType.java
  rest/src/main/java/com/wherecar/rest/dto/CarLogDetailResponse.java
  rest/src/main/java/com/wherecar/rest/dto/CarLogsResponse.java
  rest/src/main/java/com/wherecar/rest/dto/CarLogsUpdateRequest.java
  rest/src/main/java/com/wherecar/rest/dto/CarResponse.java
  rest/src/main/java/com/wherecar/rest/repository/CarLogRepository.java
  rest/src/main/java/com/wherecar/rest/repository/CarRepository.java
  rest/src/main/java/com/wherecar/rest/repository/CarStatusRepository.java
  rest/src/main/java/com/wherecar/rest/service/CarLogService.java
  rest/src/main/java/com/wherecar/rest/service/CarLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/service/CarService.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
Labels: ✨ Feature

#65 [#64] fix: 변수 에러 수정
  rest/src/main/java/com/wherecar/rest/service/CarLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
Labels: 🐞 Bugfix

#67 [#61] feat: GpsLogs API 구현
  rest/src/main/java/com/wherecar/rest/RestApplication.java
  rest/src/main/java/com/wherecar/rest/controller/GpsLogController.java
  rest/src/main/java/com/wherecar/rest/domain/GpsLog.java
  rest/src/main/java/com/wherecar/rest/dto/GpsLogRequest.java
  rest/src/main/java/com/wherecar/rest/dto/GpsLogResponse.java
  rest/src/main/java/com/wherecar/rest/dto/GpsPoint.java
  rest/src/main/java/com/wherecar/rest/dto/GpsRouteResponse.java
  rest/src/main/java/com/wherecar/rest/repository/GpsLogRepository.java
  rest/src/main/java/com/wherecar/rest/service/GpsLogService.java
  rest/src/main/java/com/wherecar/rest/service/GpsLogServiceImpl.java
Labels: ✨ Feature

#71 [#70] feat: GpsLogs 엔티티에 Car대신 mdn 추가 및 JPA 변경
  rest/src/main/java/com/wherecar/rest/domain/GpsLog.java
  rest/src/main/java/com/wherecar/rest/repository/GpsLogRepository.java
  rest/src/main/java/com/wherecar/rest/service/GpsLogServiceImpl.java
Labels: ✨ Feature

#60 [#42] feat: geoInfo 관리기능 개발
  rest/src/main/java/com/wherecar/rest/controller/GeoInfoController.java
  rest/src/main/java/com/wherecar/rest/domain/GeoInfo.java
  rest/src/main/java/com/wherecar/rest/domain/GeoLog.java
  rest/src/main/java/com/wherecar/rest/dto/ControlGeoList.java
  rest/src/main/java/com/wherecar/rest/dto/GeoFenceResponse.java
  rest/src/main/java/com/wherecar/rest/dto/GeoInfoRegistRequest.java
  rest/src/main/java/com/wherecar/rest/dto/GeoInfoRequest.java
  rest/src/main/java/com/wherecar/rest/dto/GeoInfoResponse.java
  rest/src/main/java/com/wherecar/rest/dto/GeoList.java
  rest/src/main/java/com/wherecar/rest/repository/GeoInfoRepository.java
  rest/src/main/java/com/wherecar/rest/service/GeoInfoService.java
  rest/src/main/java/com/wherecar/rest/service/GeoInfoServiceImpl.java
Labels: ✨ Feature

#78 [#44] feat: 에뮬레이터 주기 정보 전달 기능 구현
  emulator/build.gradle
  emulator/src/main/java/com/where_car/emulator/device/controller/.keep
  emulator/src/main/java/com/where_car/emulator/device/controller/DeviceWebController.java
  emulator/src/main/java/com/where_car/emulator/device/domain/CarStart.java
  emulator/src/main/java/com/where_car/emulator/device/domain/CarStop.java
  emulator/src/main/java/com/where_car/emulator/device/domain/CycleInfo.java
  emulator/src/main/java/com/where_car/emulator/device/domain/DeviceEntity.java
  emulator/src/main/java/com/where_car/emulator/device/domain/common/CarCycleInfo.java
  emulator/src/main/java/com/where_car/emulator/device/domain/common/CarIdentity.java
  emulator/src/main/java/com/where_car/emulator/device/dto/.keep
  emulator/src/main/java/com/where_car/emulator/device/dto/CarStartDto.java
  emulator/src/main/java/com/where_car/emulator/device/dto/CarStopDto.java
  emulator/src/main/java/com/where_car/emulator/device/dto/CycleInfoDto.java
  emulator/src/main/java/com/where_car/emulator/device/repository/.keep
  emulator/src/main/java/com/where_car/emulator/device/repository/JsonDatabase.java
  emulator/src/main/java/com/where_car/emulator/device/service/.keep
  emulator/src/main/java/com/where_car/emulator/device/service/DeviceService.java
  emulator/src/main/java/com/where_car/emulator/global/config/.keep
  emulator/src/main/java/com/where_car/emulator/global/config/RestTemplateConfig.java
  emulator/src/main/java/com/where_car/emulator/global/constants/DateConstant.java
  emulator/src/main/java/com/where_car/emulator/global/utill/FileNameUtil.java
  emulator/src/main/java/com/where_car/emulator/gps_module/dto/GpsPointDto.java
  emulator/src/main/java/com/where_car/emulator/gps_module/service/GpsPathService.java
  emulator/src/main/java/com/where_car/emulator/gps_module/service/GpsService.java
  emulator/src/main/resources/application-dev.yml
  emulator/src/main/resources/application.yml
  emulator/src/main/resources/gpx/gwangju-to-muju_formatted.gpx
  emulator/src/main/resources/gpx/gyeongju-to-seoul_no_ns.gpx
  emulator/src/main/resources/gpx/seoul-to-gyeongju_formatted.gpx
  emulator/src/main/resources/gpx/suwon-daejon-gumi-optimized.gpx
  emulator/src/main/resources/gpx/yangyang-to-daegu_formatted.gpx
  emulator/src/main/resources/gpx/yeosu-to-cheonan_formatted.gpx
  emulator/src/main/resources/templates/dashboard.html
  emulator/src/main/resources/templates/error/404.html
  emulator/src/main/resources/templates/error/500.html
Labels: ✨ Feature

#83 [#80] modify: DTO 필드 전부 String으로 변환
  collector/src/main/java/com/wherecar/collector/dto/CarLogRequest.java
  collector/src/main/java/com/wherecar/collector/dto/GpsLogInfo.java
  collector/src/main/java/com/wherecar/collector/dto/GpsLogRequest.java
  collector/src/main/java/com/wherecar/collector/service/CarLogConverterServiceImpl.java
  collector/src/main/java/com/wherecar/collector/service/GpsLogConverterServiceImpl.java
Labels: ✏️ Modify

#86 [#85] chore: MariaDB에서 MySQL로 변경
  rest/build.gradle
  rest/src/main/resources/application.properties
Labels: ⚙ Chore

#94 [#89] feat: 운행일지 조회 API 필터링 기능 추가
  rest/src/main/java/com/wherecar/rest/controller/CarLogController.java
  rest/src/main/java/com/wherecar/rest/dto/CarLogFilterRequest.java
  rest/src/main/java/com/wherecar/rest/dto/CarLogsResponse.java
  rest/src/main/java/com/wherecar/rest/repository/CarLogRepository.java
  rest/src/main/java/com/wherecar/rest/service/CarLogService.java
  rest/src/main/java/com/wherecar/rest/service/CarLogServiceImpl.java
  rest/src/main/resources/application.properties
Labels: ✨ Feature

#96 [#91] fix: 에뮬레이터 오류 수정
  collector/src/main/java/com/wherecar/collector/domain/CarLog.java
  collector/src/main/java/com/wherecar/collector/domain/CarStatus.java
  collector/src/main/java/com/wherecar/collector/dto/CarLogRequest.java
  collector/src/main/java/com/wherecar/collector/dto/GpsLogInfo.java
  collector/src/main/java/com/wherecar/collector/dto/GpsLogRequest.java
  collector/src/main/java/com/wherecar/collector/service/CarLogConverterServiceImpl.java
  collector/src/main/java/com/wherecar/collector/service/GpsLogConverterServiceImpl.java
  device_db.json
  emulator/src/main/java/com/where_car/emulator/device/domain/CycleInfo.java
  emulator/src/main/java/com/where_car/emulator/device/service/DeviceService.java
  emulator/src/main/resources/application.yml
Labels: 🐞 Bugfix

#101 [#100] feat: 추가 cors 해더 관련 문제 해결
  rest/src/main/java/com/wherecar/rest/config/SecurityConfig.java
  rest/src/main/java/com/wherecar/rest/user/controller/UserController.java
Labels: 🐞 Bugfix, ✨ Feature

#104 [#103] fix: api 반환값 void로 수정
  rest/src/main/java/com/wherecar/rest/controller/CarController.java
  rest/src/main/java/com/wherecar/rest/controller/CarLogController.java
  rest/src/main/java/com/wherecar/rest/controller/CompanyController.java
  rest/src/main/java/com/wherecar/rest/controller/GeoInfoController.java
  rest/src/main/java/com/wherecar/rest/controller/GeoLogController.java
  rest/src/main/java/com/wherecar/rest/domain/CarLog.java
Labels: ✨ Feature

#102 [#97] feat: 공지 사항 기능 추가
  collector/src/main/java/com/wherecar/collector/domain/Car.java
  collector/src/main/java/com/wherecar/collector/domain/CarLog.java
  collector/src/main/java/com/wherecar/collector/domain/CarStatus.java
  collector/src/main/java/com/wherecar/collector/domain/Company.java
  collector/src/main/java/com/wherecar/collector/domain/GeoInfo.java
  collector/src/main/java/com/wherecar/collector/domain/GeoLog.java
  collector/src/main/java/com/wherecar/collector/domain/GpsLog.java
  collector/src/main/java/com/wherecar/collector/domain/User.java
  rest/src/main/java/com/wherecar/rest/announcement/controller/AnnouncementController.java
  rest/src/main/java/com/wherecar/rest/announcement/domain/Announcement.java
  rest/src/main/java/com/wherecar/rest/announcement/domain/AnnouncementType.java
  rest/src/main/java/com/wherecar/rest/announcement/dto/AnnouncementDetailResponse.java
  rest/src/main/java/com/wherecar/rest/announcement/dto/AnnouncementRegisterRequest.java
  rest/src/main/java/com/wherecar/rest/announcement/dto/AnnouncementUpdateRequest.java
  rest/src/main/java/com/wherecar/rest/announcement/dto/AnnouncementsResponse.java
  rest/src/main/java/com/wherecar/rest/announcement/repository/AnnouncementRepository.java
  rest/src/main/java/com/wherecar/rest/announcement/service/AnnouncementService.java
  rest/src/main/java/com/wherecar/rest/announcement/service/AnnouncementServiceImpl.java
  rest/src/main/java/com/wherecar/rest/service/CarLogServiceImpl.java
Labels: ✨ Feature

#114 [#111] modify: 공지 사항 content 타입 변경
  rest/src/main/java/com/wherecar/rest/announcement/domain/Announcement.java
Labels: ✏️ Modify

#124 [#122] feat: 차량 실시간 위치 전송 웹소켓 구현
  rest/build.gradle
  rest/src/main/java/com/wherecar/rest/RestApplication.java
  rest/src/main/java/com/wherecar/rest/dto/GpsPoint.java
  rest/src/main/java/com/wherecar/rest/websocket/CarLocationSocketHandler.java
  rest/src/main/java/com/wherecar/rest/websocket/LocationBroadcaster.java
  rest/src/main/java/com/wherecar/rest/websocket/config/WebSocketConfig.java
Labels: ✨ Feature

#139 [#138] fix: 웹소켓에 미관제 차량 조회 안하도록 수정
  rest/src/main/java/com/wherecar/rest/repository/CarRepository.java
  rest/src/main/java/com/wherecar/rest/service/CarService.java
  rest/src/main/java/com/wherecar/rest/service/CarServiceImpl.java
  rest/src/main/java/com/wherecar/rest/websocket/CarLocationSocketHandler.java
Labels: ✨ Feature

#154 [#153] refactor: Company, User, Permission 리펙토링 완료
  rest/src/main/java/com/wherecar/rest/common/config/PermissionConfig.java
  rest/src/main/java/com/wherecar/rest/company/application/CompanyService.java
  rest/src/main/java/com/wherecar/rest/company/application/CompanyServiceImpl.java
  rest/src/main/java/com/wherecar/rest/company/domain/Company.java
  rest/src/main/java/com/wherecar/rest/company/domain/CompanyFactory.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyReader.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyReaderImpl.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyStore.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyStoreImpl.java
  rest/src/main/java/com/wherecar/rest/user/application/UserService.java
  rest/src/main/java/com/wherecar/rest/user/application/UserServiceImpl.java
  rest/src/main/java/com/wherecar/rest/user/domain/User.java
  rest/src/main/java/com/wherecar/rest/user/domain/UserFactory.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserReader.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserReaderImpl.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserStore.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserStoreImpl.java
Labels: 🔨 Refactor

#156 [#155] refactor: Announcement 리펙토링 완료
  rest/src/main/java/com/wherecar/rest/announcement/application/AnnouncementService.java
  rest/src/main/java/com/wherecar/rest/announcement/application/AnnouncementServiceImpl.java
  rest/src/main/java/com/wherecar/rest/announcement/application/dto/AnnouncementRegisterRequest.java
  rest/src/main/java/com/wherecar/rest/announcement/application/dto/AnnouncementRequest.java
  rest/src/main/java/com/wherecar/rest/announcement/application/dto/AnnouncementResponse.java
  rest/src/main/java/com/wherecar/rest/announcement/application/dto/AnnouncementsResponse.java
  rest/src/main/java/com/wherecar/rest/announcement/domain/Announcement.java
  rest/src/main/java/com/wherecar/rest/announcement/domain/AnnouncementFactory.java
  rest/src/main/java/com/wherecar/rest/announcement/infrastructure/AnnouncementReader.java
  rest/src/main/java/com/wherecar/rest/announcement/infrastructure/AnnouncementReaderImpl.java
  rest/src/main/java/com/wherecar/rest/announcement/infrastructure/AnnouncementStore.java
  rest/src/main/java/com/wherecar/rest/announcement/infrastructure/AnnouncementStoreImpl.java
  rest/src/main/java/com/wherecar/rest/announcement/presentation/AnnouncementController.java
Labels: 🔨 Refactor

#161 [#160] refactor: GeoInfo 리팩토링 완료
  rest/src/main/java/com/wherecar/rest/company/application/CompanyServiceImpl.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyReader.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyReaderImpl.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyStore.java
  rest/src/main/java/com/wherecar/rest/company/infrastructure/CompanyStoreImpl.java
  rest/src/main/java/com/wherecar/rest/geoinfo/application/GeoInfoService.java
  rest/src/main/java/com/wherecar/rest/geoinfo/application/GeoInfoServiceImpl.java
  rest/src/main/java/com/wherecar/rest/geoinfo/domain/GeoInfo.java
  rest/src/main/java/com/wherecar/rest/geoinfo/domain/GeoInfoFactory.java
  rest/src/main/java/com/wherecar/rest/geoinfo/infrastructure/GeoInfoReader.java
  rest/src/main/java/com/wherecar/rest/geoinfo/infrastructure/GeoInfoReaderImpl.java
  rest/src/main/java/com/wherecar/rest/geoinfo/infrastructure/GeoInfoStore.java
  rest/src/main/java/com/wherecar/rest/geoinfo/infrastructure/GeoInfoStoreImpl.java
  rest/src/main/java/com/wherecar/rest/geoinfo/presentation/GeoInfoController.java
  rest/src/main/java/com/wherecar/rest/user/application/UserServiceImpl.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserStore.java
  rest/src/main/java/com/wherecar/rest/user/infrastructure/UserStoreImpl.java
Labels: 🔨 Refactor

#170 [#145] refactor: GeoLog 리펙토링 작업
  rest/src/main/java/com/wherecar/rest/geolog/application/GeoLogService.java
  rest/src/main/java/com/wherecar/rest/geolog/application/GeoLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/geolog/domain/GeoLog.java
  rest/src/main/java/com/wherecar/rest/geolog/domain/GeoLogFactory.java
  rest/src/main/java/com/wherecar/rest/geolog/infrastructure/GeoLogReader.java
  rest/src/main/java/com/wherecar/rest/geolog/infrastructure/GeoLogReaderImpl.java
  rest/src/main/java/com/wherecar/rest/geolog/infrastructure/GeoLogRepository.java
  rest/src/main/java/com/wherecar/rest/geolog/infrastructure/GeoLogStore.java
  rest/src/main/java/com/wherecar/rest/geolog/infrastructure/GeoLogStoreImpl.java
  rest/src/main/java/com/wherecar/rest/geolog/presentation/GeoLogController.java
  rest/src/main/java/com/wherecar/rest/gpslog/presentation/GpsLogController.java
Labels: 🔨 Refactor

#169 [#167] refactor: GpsLog 리펙토링 작업
  rest/src/main/java/com/wherecar/rest/gpslog/application/GpsLogService.java
  rest/src/main/java/com/wherecar/rest/gpslog/application/GpsLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/gpslog/domain/GpsLogFactory.java
  rest/src/main/java/com/wherecar/rest/gpslog/infrastructure/GpsLogReader.java
  rest/src/main/java/com/wherecar/rest/gpslog/infrastructure/GpsLogReaderImpl.java
  rest/src/main/java/com/wherecar/rest/gpslog/presentation/GpsLogController.java
  rest/src/main/java/com/wherecar/rest/websocket/CarLocationSocketHandler.java
Labels: 🔨 Refactor

#168 [#166] refactor: CarLog 도메인 코드 리팩토링
  rest/src/main/java/com/wherecar/rest/car/application/CarServiceImpl.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarReader.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarReaderImpl.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarStore.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarStoreImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/application/CarLogService.java
  rest/src/main/java/com/wherecar/rest/carlog/application/CarLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/application/dto/CarLogResponse.java
  rest/src/main/java/com/wherecar/rest/carlog/domain/CarLog.java
  rest/src/main/java/com/wherecar/rest/carlog/domain/CarLogFactory.java
  rest/src/main/java/com/wherecar/rest/carlog/infrastructure/CarLogReader.java
  rest/src/main/java/com/wherecar/rest/carlog/infrastructure/CarLogReaderImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/infrastructure/CarLogRepository.java
  rest/src/main/java/com/wherecar/rest/carlog/infrastructure/CarLogStore.java
  rest/src/main/java/com/wherecar/rest/carlog/infrastructure/CarLogStoreImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/presentation/CarLogController.java
Labels: 🔨 Refactor

#173 [#172] init: 배치서버 생성
  batch/.gitattributes
  batch/.gitignore
  batch/build.gradle
  batch/gradle/wrapper/gradle-wrapper.jar
  batch/gradle/wrapper/gradle-wrapper.properties
  batch/gradlew
  batch/gradlew.bat
  batch/settings.gradle
  batch/src/main/java/com/wherecar/batch/BatchApplication.java
  batch/src/main/resources/application.properties
  batch/src/test/java/com/wherecar/batch/BatchApplicationTests.java
  settings.gradle
Labels: 📦️ package

#178 [#177] fix: 잘못된 경로 수정 및 메서드 인자 순서 수정
  rest/src/main/java/com/wherecar/rest/geoinfo/presentation/GeoInfoController.java
  rest/src/main/java/com/wherecar/rest/geolog/application/GeoLogServiceImpl.java
Labels: 🐞 Bugfix

#186 [#179] feat: JWT refresh 토큰 Redis 관리 기능 구현
  docker/docker-compose-dev.yml
  rest/build.gradle
  rest/src/main/java/com/wherecar/rest/common/config/RedisConfig.java
  rest/src/main/java/com/wherecar/rest/common/exception/TokenValidationException.java
  rest/src/main/java/com/wherecar/rest/security/config/.empty
  rest/src/main/java/com/wherecar/rest/security/config/SecurityConfig.java
  rest/src/main/java/com/wherecar/rest/security/jwt/CookieUtil.java
  rest/src/main/java/com/wherecar/rest/security/jwt/CustomUserDetailsService.java
  rest/src/main/java/com/wherecar/rest/security/jwt/JWTFilter.java
  rest/src/main/java/com/wherecar/rest/security/jwt/JWTUtil.java
  rest/src/main/java/com/wherecar/rest/security/jwt/LoginFilter.java
  rest/src/main/java/com/wherecar/rest/security/jwt/TokenController.java
  rest/src/main/java/com/wherecar/rest/security/jwt/TokenService.java
  rest/src/main/java/com/wherecar/rest/security/jwt/dto/TokenPair.java
  rest/src/main/resources/application-dev.yml
  rest/src/main/resources/application-prod.yml
  rest/src/main/resources/application.yml
Labels: ✨ Feature

#184 [#183] feat: rest 다중 db 설정 및 통계 API 생성
  rest/src/main/java/com/wherecar/rest/carlog/domain/constant/DriveType.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/application/CarLogSummaryService.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/application/CarLogSummaryServiceImpl.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/application/dto/CarLogSummaryOverviewResponse.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/domain/CarLogSummary.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/domain/CarLogSummaryFactory.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/infrastructure/CarLogSummaryReader.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/infrastructure/CarLogSummaryReaderImpl.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/infrastructure/CarLogSummaryRepository.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/presentation/CarLogSummaryController.java
  rest/src/main/java/com/wherecar/rest/common/config/MainDataSourceConfig.java
  rest/src/main/java/com/wherecar/rest/common/config/StatDataSourceConfig.java
  rest/src/main/resources/application-dev.yml
  rest/src/main/resources/application-prod.yml
  rest/src/main/resources/sql/car_log_summaries.sql
Labels: ✨ Feature

#189 [#187] modify: 각 필드 데이터 올바른 타입으로 수정
  rest/src/main/java/com/wherecar/rest/car/application/dto/CarRegisterRequest.java
  rest/src/main/java/com/wherecar/rest/car/application/dto/CarResponse.java
  rest/src/main/java/com/wherecar/rest/car/domain/CarStatus.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarRepository.java
  rest/src/main/java/com/wherecar/rest/car/infrastructure/CarStatusRepository.java
  rest/src/main/java/com/wherecar/rest/carlog/application/CarLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/application/dto/CarLogDetailResponse.java
  rest/src/main/java/com/wherecar/rest/carlog/application/dto/CarLogResponse.java
  rest/src/main/java/com/wherecar/rest/carlog/application/dto/MonthlyMileage.java
  rest/src/main/java/com/wherecar/rest/carlog/domain/CarLog.java
Labels: ✏️ Modify

#205 [#204] feat: JWT, Login Filter에 BaseResponse 적용
  rest/src/main/java/com/wherecar/rest/security/jwt/JWTFilter.java
  rest/src/main/java/com/wherecar/rest/security/jwt/LoginFilter.java
Labels: ✨ Feature

#206 [#199] modify: 모든 컨트롤러 ResponseEntity<BaseResponse<T>> 로 리턴하도록 변경
  rest/src/main/java/com/wherecar/rest/announcement/presentation/AnnouncementController.java
  rest/src/main/java/com/wherecar/rest/car/presentation/CarController.java
  rest/src/main/java/com/wherecar/rest/carlog/application/CarLogService.java
  rest/src/main/java/com/wherecar/rest/carlog/application/CarLogServiceImpl.java
  rest/src/main/java/com/wherecar/rest/carlog/presentation/CarLogController.java
  rest/src/main/java/com/wherecar/rest/carlogsummary/presentation/CarLogSummaryController.java
  rest/src/main/java/com/wherecar/rest/common/exception/GlobalExceptionHandler.java
  rest/src/main/java/com/wherecar/rest/common/response/BaseResponse.java
  rest/src/main/java/com/wherecar/rest/company/presentation/CompanyController.java
  rest/src/main/java/com/wherecar/rest/geoinfo/application/dto/GeoInfoResponse.java
  rest/src/main/java/com/wherecar/rest/geoinfo/application/dto/emulator/GeoResponse.java
  rest/src/main/java/com/wherecar/rest/geoinfo/presentation/GeoInfoController.java
  rest/src/main/java/com/wherecar/rest/geolog/presentation/GeoLogController.java
  rest/src/main/java/com/wherecar/rest/gpslog/application/dto/GpsLogResponse.java
  rest/src/main/java/com/wherecar/rest/gpslog/presentation/GpsLogController.java
  rest/src/main/java/com/wherecar/rest/user/presentation/UserController.java
Labels: ✏️ Modify

#197 [#190] feat: 에뮬레이터 토큰 발급 및 유효성 검증 로직 구현
  rest/src/main/java/com/wherecar/rest/emulauth/application/EmulAuthService.java
  rest/src/main/java/com/wherecar/rest/emulauth/application/EmulAuthServiceImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/application/dto/EmulTokenRequest.java
  rest/src/main/java/com/wherecar/rest/emulauth/application/dto/EmulTokenResponse.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/config/WebConfig.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/interceptor/TokenAuthInterceptor.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/application/TokenValidationResult.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/application/TokenValidationService.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/application/dto/EmulTokenResponse.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/infrastructure/EmulTokenReader.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/infrastructure/EmulTokenReaderImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/infrastructure/EmulTokenStore.java
  rest/src/main/java/com/wherecar/rest/emulauth/infrastructure/EmulTokenStoreImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/presentation/EmulAuthController.java
  rest/src/main/java/com/wherecar/rest/security/config/SecurityConfig.java
Labels: ✨ Feature

#214 [#208] fix: security코드에 변경된 BaseResponse 적용
  rest/src/main/java/com/wherecar/rest/common/constants/ErrorCode.java
  rest/src/main/java/com/wherecar/rest/security/jwt/JWTFilter.java
  rest/src/main/java/com/wherecar/rest/security/jwt/LoginFilter.java
Labels: 🐞 Bugfix, ✨ Feature

#213 [#209] feat: collector 로그 작업
  collector/src/main/java/com/wherecar/collector/carlog/application/CarLogConsumerServiceImpl.java
  collector/src/main/java/com/wherecar/collector/carlog/application/CarLogServiceImpl.java
  collector/src/main/java/com/wherecar/collector/carlog/application/dto/CarLogRequest.java
  collector/src/main/java/com/wherecar/collector/carlog/application/dto/CarLogResponse.java
  collector/src/main/java/com/wherecar/collector/gpslog/application/GpsLogConsumerServiceImpl.java
  collector/src/main/java/com/wherecar/collector/gpslog/application/GpsLogServiceImpl.java
  collector/src/main/java/com/wherecar/collector/gpslog/application/dto/GpsLogInfo.java
  collector/src/main/java/com/wherecar/collector/gpslog/application/dto/GpsLogRequest.java
  collector/src/main/java/com/wherecar/collector/gpslog/application/dto/GpsLogResponse.java
  device_db.json
  hub/src/main/java/com/wherecar/hub/carlog/application/dto/CarLogRequest.java
  hub/src/main/java/com/wherecar/hub/gpslog/application/dto/GpsLogInfo.java
  hub/src/main/java/com/wherecar/hub/gpslog/application/dto/GpsLogRequest.java
Labels: ✨ Feature

#221 [#220] fix: 중복된 application 제거
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/applicatiom/TokenValidationResult.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/applicatiom/TokenValidationService.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/applicatiom/dto/EmulTokenResponse.java
Labels: 🐞 Bugfix

#235 [#234] fix: 이메일 검증 안 되는 버그 수정
  rest/src/main/java/com/wherecar/rest/car/application/dto/CarRegisterRequest.java
  rest/src/main/java/com/wherecar/rest/user/application/dto/RootUserRequest.java
  rest/src/main/java/com/wherecar/rest/user/application/dto/SubUserRequest.java
Labels: 🐞 Bugfix

#233 [#299] EmulToken 발급(Redis) -> JWT로 변경
  hub/build.gradle
  hub/src/main/java/com/wherecar/hub/common/config/WebConfig.java
  hub/src/main/java/com/wherecar/hub/common/interceptor/TokenAuthInterceptor.java
  hub/src/main/java/com/wherecar/hub/common/jwt/EmulJWTUtil.java
  hub/src/main/java/com/wherecar/hub/token/application/TokenValidationResult.java
  hub/src/main/java/com/wherecar/hub/token/application/TokenValidationService.java
  hub/src/main/java/com/wherecar/hub/token/application/dto/EmulTokenResponse.java
  hub/src/main/resources/application-dev.yml
  hub/src/main/resources/application-prod.yml
  rest/src/main/java/com/wherecar/rest/emulauth/application/EmulAuthServiceImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/application/TokenValidationService.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/infrastructure/EmulTokenReader.java
  rest/src/main/java/com/wherecar/rest/emulauth/hubtmp/token/infrastructure/EmulTokenReaderImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/infrastructure/EmulTokenStore.java
  rest/src/main/java/com/wherecar/rest/emulauth/infrastructure/EmulTokenStoreImpl.java
  rest/src/main/java/com/wherecar/rest/emulauth/jwt/EmulJWTUtil.java
  rest/src/main/java/com/wherecar/rest/emulauth/presentation/EmulAuthController.java
  rest/src/main/java/com/wherecar/rest/security/jwt/JWTUtil.java
  rest/src/main/resources/application-dev.yml
  rest/src/main/resources/application-prod.yml
Labels: ✨ Feature

#238 [#237] fix: 허브 토큰 만료 시 HTTP 200 상태로 에러 응답하도록 수정
  hub/src/main/java/com/wherecar/hub/common/interceptor/TokenAuthInterceptor.java
  rest/src/main/java/com/wherecar/rest/emulauth/application/dto/EmulTokenRequest.java
Labels: ✨ Feature
